apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
apiServer:
  extraArgs:
    anonymous-auth: "false"
    enable-admission-plugins: EventRateLimit,ImagePolicyWebhook,NodeRestriction,PodSecurityPolicy
networking:
  serviceSubnet: "10.96.0.0/12"
  podSubnet: "10.100.0.1/24"
  dnsDomain: "cluster.local"
#controlPlaneEndpoint: "10.100.0.1:6443????" only for HA this would be LB

# calico default:
# - name: CALICO_IPV4POOL_CIDR
#   value: "192.168.0.0/16"
