apiVersion: v1
kind: Pod
metadata:
  name: seccomp-app
  namespace: seccomp-test
  annotations:
    seccomp.security.alpha.kubernetes.io/pod: "localhost/default-profile.json"
    # you can specify seccomp profile per container. If you add another profile you can configure
    # it for a specific container - 'pause' in this case.
    # container.seccomp.security.alpha.kubernetes.io/pause: "localhost/some-other-profile.json"
spec:
  containers:
  - name: alpine-seccomp
    image: alpine:latest
    command: ["sleep", "3600"]
