---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: psp:permissive
rules:
- apiGroups:
  - policy
  resourceNames:
  - permissive
  resources:
  - podsecuritypolicies
  verbs:
  - use

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: psp:permissive:binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: psp:permissive
subjects:
  - kind: ServiceAccount
    name: replicaset-controller
    namespace: kube-system
  - kind: ServiceAccount
    name: rook-edgefs-system
    namespace: rook-edgefs-system
  - kind: ServiceAccount
    name: calico-node
    namespace: kube-system