---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: psp:selinux
rules:
- apiGroups:
  - policy
  resourceNames:
  - just-selinux
  resources:
  - podsecuritypolicies
  verbs:
  - use

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: psp:just-selinux:binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: psp:selinux
subjects:
  - kind: ServiceAccount
    name: selinux-sa
    namespace: selinux
